name: Go

on:
  push:
    branches: [ master ]
  pull_request: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.18"
          - "1.19"
          - "1.20"
          - "1.21"
        redis-version:
          - 4
          - 5
          - 6

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Setup Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./...

  imports:
    name: Imports
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Check imports
        run: |
          if [ "$(goimports -l . | wc -l)" -gt 0 ]; then
            echo "The following files need goimports formatting:"
            goimports -l .
            echo "Run 'goimports -w .' to fix"
            exit 1
          fi

  ## Checks to be enabled in the future:

  # errcheck:
  #   name: Errcheck
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: '1.21'
  #     - name: Install errcheck
  #       run: go install github.com/kisielk/errcheck@latest
  #     - name: Run errcheck
  #       run: errcheck ./...

  # lint:
  #   name: Lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: '1.21'
  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v4
  #       with:
  #         version: latest

  # staticcheck:
  #   name: StaticCheck
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: '1.21'
  #     - name: Install staticcheck
  #       run: go install honnef.co/go/tools/cmd/staticcheck@latest
  #     - name: Run staticcheck
  #       run: staticcheck ./...

  # sec:
  #   name: Sec
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: '1.21'
  #     - name: Install gosec
  #       run: go install github.com/securego/gosec/v2/cmd/gosec@latest
  #     - name: Run gosec
  #       run: gosec ./...